public enum E_Event
{
    NONE = -1,
    CLICK, // 예제 타입
    SPAWN_STOP,
    SPAWN_START,
    NOTE_CLEAR,
    BOSSRUSH,
    STAGE_END,
    BOSSDEAD,
    CHANGED_SCENE,
    ENTERCONTACT,
    CHANGED_BGM,
    CONTACTEND,
    PLAYERDEAD,
    ENTERBOSS,
    E_EVENT_MAX,
}